package sk.uniba.fmph.dcs.terra_futura.actions;

import org.apache.commons.lang3.tuple.Pair;
import sk.uniba.fmph.dcs.terra_futura.game.GridPosition;
import sk.uniba.fmph.dcs.terra_futura.enums.Resource;
import sk.uniba.fmph.dcs.terra_futura.game.Card;
import sk.uniba.fmph.dcs.terra_futura.game.Grid;

import java.util.List;
import java.util.Objects;

/**
 * Represents a standard process action where a card is activated within the
 * player's grid.
 * Delegates the resource transfer logic to {@link ResourceTransferService}.
 */
public class ProcessAction {
    private final ResourceTransferService transferService;

    /**
     * Constructs a ProcessAction with the specified transfer service.
     *
     * @param transferService The service to handle resource transfers.
     * @throws NullPointerException if transferService is null.
     */
    public ProcessAction(final ResourceTransferService transferService) {
        this.transferService = Objects.requireNonNull(transferService, "transferService cannot be null");
    }

    /**
     * Default constructor initializing with a new ResourceTransferService.
     */
    public ProcessAction() {
        this(new ResourceTransferService());
    }

    /**
     * Activates a card and executes the associated resource transaction.
     *
     * @param card      The card being activated.
     * @param grid      The game grid.
     * @param inputs    Resources required for the action.
     * @param outputs   Resources produced by the action.
     * @param pollution Pollution generated by the action.
     * @return true if the activation was successful, false otherwise.
     */
    public boolean activateCard(final Card card, final Grid grid, final List<Pair<Resource, GridPosition>> inputs,
            final List<Pair<Resource, GridPosition>> outputs, final List<GridPosition> pollution) {

        if (card == null) {
            return false;
        }
        return transferService.executeTransaction(grid, inputs, outputs, pollution);
    }
}
